# Generated by Django 4.1.6 on 2024-11-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='pic4.jpg', upload_to='profile_pics'),
        ),
    ]
